"""SQLite/Postgres-persistenssi autotraderille ja Telegram-tilalle."""

from __future__ import annotations

import json
import os
import sqlite3
from datetime import date
from pathlib import Path
from typing import Any

from autotrader.metrics import EquityPoint
from autotrader.portfolio import ProposedOrder


def _now_sql() -> str:
    return "CURRENT_TIMESTAMP"


class Storage:
    """Yhteinen DB-kerros SQLite- ja Postgres-ajolle."""

    def __init__(self, database_url: str | None = None):
        self.database_url = database_url or os.getenv("DATABASE_URL", "sqlite:///autotrader.sqlite3")
        self.is_postgres = self.database_url.startswith(("postgres://", "postgresql://"))
        self.conn = self._connect()
        self.ensure_schema()

    def _connect(self):
        if self.is_postgres:
            import psycopg

            return psycopg.connect(self.database_url)

        if self.database_url.startswith("sqlite:///"):
            db_path = self.database_url.removeprefix("sqlite:///")
        else:
            db_path = self.database_url
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(db_path, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        return conn

    def _sql(self, sql: str) -> str:
        if self.is_postgres:
            return sql.replace("?", "%s")
        return sql

    def execute(self, sql: str, params: tuple[Any, ...] = ()):
        cursor = self.conn.cursor()
        cursor.execute(self._sql(sql), params)
        self.conn.commit()
        return cursor

    def fetchone(self, sql: str, params: tuple[Any, ...] = ()) -> dict[str, Any] | None:
        cursor = self.conn.cursor()
        cursor.execute(self._sql(sql), params)
        row = cursor.fetchone()
        if row is None:
            return None
        if isinstance(row, sqlite3.Row):
            return dict(row)
        columns = [item[0] for item in cursor.description]
        return dict(zip(columns, row))

    def fetchall(self, sql: str, params: tuple[Any, ...] = ()) -> list[dict[str, Any]]:
        cursor = self.conn.cursor()
        cursor.execute(self._sql(sql), params)
        rows = cursor.fetchall()
        if not rows:
            return []
        if isinstance(rows[0], sqlite3.Row):
            return [dict(row) for row in rows]
        columns = [item[0] for item in cursor.description]
        return [dict(zip(columns, row)) for row in rows]

    def ensure_schema(self) -> None:
        """Luo tarvittavat taulut idempotentisti."""
        pk = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.is_postgres else "INTEGER PRIMARY KEY AUTOINCREMENT"
        timestamp = "TIMESTAMPTZ" if self.is_postgres else "TEXT"
        bool_type = "BOOLEAN" if self.is_postgres else "INTEGER"
        bool_default_false = "FALSE" if self.is_postgres else "0"

        statements = [
            f"""
            CREATE TABLE IF NOT EXISTS autotrader_runs (
                id {pk},
                run_date DATE NOT NULL UNIQUE,
                status TEXT NOT NULL,
                broker TEXT NOT NULL,
                dry_run {bool_type} NOT NULL DEFAULT {bool_default_false},
                started_at {timestamp} NOT NULL DEFAULT ({_now_sql()}),
                finished_at {timestamp},
                metadata_json TEXT,
                error TEXT
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS autotrader_decisions (
                id {pk},
                run_id INTEGER NOT NULL,
                ticker TEXT NOT NULL,
                decision TEXT NOT NULL,
                score REAL,
                final_state_json TEXT,
                error TEXT,
                created_at {timestamp} NOT NULL DEFAULT ({_now_sql()}),
                UNIQUE (run_id, ticker)
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS autotrader_orders (
                id {pk},
                run_id INTEGER NOT NULL,
                ticker TEXT NOT NULL,
                side TEXT NOT NULL,
                amount REAL NOT NULL,
                estimated_price REAL NOT NULL,
                status TEXT NOT NULL,
                reason TEXT,
                broker_order_id TEXT,
                raw_json TEXT,
                created_at {timestamp} NOT NULL DEFAULT ({_now_sql()})
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS autotrader_equity_curve (
                id {pk},
                run_date DATE NOT NULL UNIQUE,
                equity REAL NOT NULL,
                cash REAL NOT NULL,
                benchmark_symbol TEXT,
                benchmark_price REAL,
                created_at {timestamp} NOT NULL DEFAULT ({_now_sql()})
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS autotrader_uic_map (
                ticker TEXT PRIMARY KEY,
                uic INTEGER NOT NULL,
                asset_type TEXT NOT NULL DEFAULT 'Stock',
                updated_at {timestamp} NOT NULL DEFAULT ({_now_sql()})
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS autotrader_wallet (
                key TEXT PRIMARY KEY,
                value_json TEXT NOT NULL,
                updated_at {timestamp} NOT NULL DEFAULT ({_now_sql()})
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS telegram_watchlist (
                user_id TEXT NOT NULL,
                ticker TEXT NOT NULL,
                nimi TEXT NOT NULL,
                lisatty DATE NOT NULL,
                PRIMARY KEY (user_id, ticker)
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS telegram_alerts (
                user_id TEXT NOT NULL,
                ticker TEXT NOT NULL,
                nimi TEXT NOT NULL,
                tyyppi TEXT NOT NULL,
                prosentti REAL NOT NULL,
                hinta_luontihetkella REAL NOT NULL,
                luotu DATE NOT NULL,
                PRIMARY KEY (user_id, ticker)
            )
            """,
            f"""
            CREATE TABLE IF NOT EXISTS telegram_reports (
                message_id TEXT PRIMARY KEY,
                full_report TEXT NOT NULL,
                state_json TEXT,
                created_at {timestamp} NOT NULL DEFAULT ({_now_sql()})
            )
            """,
        ]

        for statement in statements:
            self.execute(statement)

    def is_run_completed(self, run_date: date | str) -> bool:
        row = self.fetchone("SELECT status FROM autotrader_runs WHERE run_date = ?", (str(run_date),))
        return bool(row and row["status"] == "completed")

    def start_run(self, run_date: date | str, broker: str, dry_run: bool, metadata: dict[str, Any] | None = None) -> int:
        metadata_json = json.dumps(metadata or {}, ensure_ascii=False)
        if self.is_postgres:
            cursor = self.conn.cursor()
            cursor.execute(
                self._sql(
                    """
                    INSERT INTO autotrader_runs (run_date, status, broker, dry_run, started_at, metadata_json)
                    VALUES (?, 'running', ?, ?, CURRENT_TIMESTAMP, ?)
                    ON CONFLICT (run_date) DO UPDATE
                        SET status = 'running',
                            broker = EXCLUDED.broker,
                            dry_run = EXCLUDED.dry_run,
                            started_at = CURRENT_TIMESTAMP,
                            finished_at = NULL,
                            metadata_json = EXCLUDED.metadata_json,
                            error = NULL
                    RETURNING id
                    """
                ),
                (str(run_date), broker, bool(dry_run), metadata_json),
            )
            row = cursor.fetchone()
            self.conn.commit()
            assert row is not None
            return int(row[0])

        self.execute(
            """
            INSERT INTO autotrader_runs (run_date, status, broker, dry_run, started_at, metadata_json)
            VALUES (?, 'running', ?, ?, CURRENT_TIMESTAMP, ?)
            ON CONFLICT (run_date) DO UPDATE
                SET status = 'running',
                    broker = excluded.broker,
                    dry_run = excluded.dry_run,
                    started_at = CURRENT_TIMESTAMP,
                    finished_at = NULL,
                    metadata_json = excluded.metadata_json,
                    error = NULL
            """,
            (str(run_date), broker, int(dry_run), metadata_json),
        )
        row = self.fetchone("SELECT id FROM autotrader_runs WHERE run_date = ?", (str(run_date),))
        assert row is not None
        return int(row["id"])

    def finish_run(self, run_id: int, status: str, error: str | None = None) -> None:
        self.execute(
            "UPDATE autotrader_runs SET status = ?, finished_at = CURRENT_TIMESTAMP, error = ? WHERE id = ?",
            (status, error, run_id),
        )

    def save_decision(
        self,
        run_id: int,
        ticker: str,
        decision: str,
        score: float | None,
        final_state: dict[str, Any] | None,
        error: str | None = None,
    ) -> None:
        self.execute(
            """
            INSERT INTO autotrader_decisions
                (run_id, ticker, decision, score, final_state_json, error)
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT (run_id, ticker) DO UPDATE
                SET decision = excluded.decision,
                    score = excluded.score,
                    final_state_json = excluded.final_state_json,
                    error = excluded.error
            """,
            (
                run_id,
                ticker,
                decision,
                score,
                json.dumps(final_state or {}, ensure_ascii=False, default=str),
                error,
            ),
        )

    def log_order(
        self,
        run_id: int,
        order: ProposedOrder,
        status: str,
        reason: str | None = None,
        broker_order_id: str | None = None,
        raw: dict[str, Any] | None = None,
    ) -> int:
        cursor = self.execute(
            """
            INSERT INTO autotrader_orders
                (run_id, ticker, side, amount, estimated_price, status, reason, broker_order_id, raw_json)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                run_id,
                order.ticker,
                order.side.value,
                order.amount,
                order.estimated_price,
                status,
                reason or order.reason,
                broker_order_id,
                json.dumps(raw or {}, ensure_ascii=False, default=str),
            ),
        )
        if self.is_postgres:
            row = self.fetchone("SELECT MAX(id) AS id FROM autotrader_orders WHERE run_id = ?", (run_id,))
            assert row is not None
            return int(row["id"])
        return int(cursor.lastrowid)

    def update_order(self, order_id: int, status: str, broker_order_id: str | None = None, raw: dict[str, Any] | None = None, reason: str | None = None) -> None:
        self.execute(
            """
            UPDATE autotrader_orders
            SET status = ?,
                broker_order_id = COALESCE(?, broker_order_id),
                raw_json = COALESCE(?, raw_json),
                reason = COALESCE(?, reason)
            WHERE id = ?
            """,
            (
                status,
                broker_order_id,
                json.dumps(raw, ensure_ascii=False, default=str) if raw is not None else None,
                reason,
                order_id,
            ),
        )

    def save_equity(self, run_date: date | str, equity: float, cash: float, benchmark_symbol: str | None = None, benchmark_price: float | None = None) -> None:
        self.execute(
            """
            INSERT INTO autotrader_equity_curve
                (run_date, equity, cash, benchmark_symbol, benchmark_price)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT (run_date) DO UPDATE
                SET equity = excluded.equity,
                    cash = excluded.cash,
                    benchmark_symbol = excluded.benchmark_symbol,
                    benchmark_price = excluded.benchmark_price
            """,
            (str(run_date), equity, cash, benchmark_symbol, benchmark_price),
        )

    def load_equity_curve(self) -> list[EquityPoint]:
        rows = self.fetchall("SELECT run_date, equity FROM autotrader_equity_curve ORDER BY run_date")
        return [EquityPoint(date=date.fromisoformat(str(row["run_date"])), equity=float(row["equity"])) for row in rows]

    def load_benchmark_prices(self, symbol: str = "^OMXHPI") -> list[float]:
        rows = self.fetchall(
            """
            SELECT benchmark_price
            FROM autotrader_equity_curve
            WHERE benchmark_symbol = ? AND benchmark_price IS NOT NULL
            ORDER BY run_date
            """,
            (symbol,),
        )
        return [float(row["benchmark_price"]) for row in rows]

    def save_uic(self, ticker: str, uic: int, asset_type: str = "Stock") -> None:
        self.execute(
            """
            INSERT INTO autotrader_uic_map (ticker, uic, asset_type, updated_at)
            VALUES (?, ?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT (ticker) DO UPDATE
                SET uic = excluded.uic,
                    asset_type = excluded.asset_type,
                    updated_at = CURRENT_TIMESTAMP
            """,
            (ticker.upper(), uic, asset_type),
        )

    def get_uic(self, ticker: str) -> int | None:
        row = self.fetchone("SELECT uic FROM autotrader_uic_map WHERE ticker = ?", (ticker.upper(),))
        return int(row["uic"]) if row else None

    def list_watchlist(self, user_id: int) -> list[dict[str, str]]:
        return self.fetchall(
            "SELECT ticker, nimi, lisatty FROM telegram_watchlist WHERE user_id = ? ORDER BY lisatty, ticker",
            (str(user_id),),
        )

    def add_watchlist_item(self, user_id: int, ticker: str, nimi: str, lisatty: str) -> None:
        self.execute(
            """
            INSERT INTO telegram_watchlist (user_id, ticker, nimi, lisatty)
            VALUES (?, ?, ?, ?)
            ON CONFLICT (user_id, ticker) DO NOTHING
            """,
            (str(user_id), ticker, nimi, lisatty),
        )

    def remove_watchlist_item(self, user_id: int, raw_name: str) -> int:
        before = self.fetchone("SELECT COUNT(*) AS count FROM telegram_watchlist WHERE user_id = ?", (str(user_id),))
        self.execute(
            """
            DELETE FROM telegram_watchlist
            WHERE user_id = ? AND (UPPER(ticker) = UPPER(?) OR UPPER(nimi) = UPPER(?))
            """,
            (str(user_id), raw_name, raw_name),
        )
        after = self.fetchone("SELECT COUNT(*) AS count FROM telegram_watchlist WHERE user_id = ?", (str(user_id),))
        return int(before["count"]) - int(after["count"]) if before and after else 0

    def list_alerts(self, user_id: int) -> list[dict[str, Any]]:
        return self.fetchall(
            """
            SELECT ticker, nimi, tyyppi, prosentti, hinta_luontihetkella, luotu
            FROM telegram_alerts
            WHERE user_id = ?
            ORDER BY luotu, ticker
            """,
            (str(user_id),),
        )

    def upsert_alert(self, user_id: int, alert: dict[str, Any]) -> None:
        self.execute(
            """
            INSERT INTO telegram_alerts
                (user_id, ticker, nimi, tyyppi, prosentti, hinta_luontihetkella, luotu)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (user_id, ticker) DO UPDATE
                SET nimi = excluded.nimi,
                    tyyppi = excluded.tyyppi,
                    prosentti = excluded.prosentti,
                    hinta_luontihetkella = excluded.hinta_luontihetkella,
                    luotu = excluded.luotu
            """,
            (
                str(user_id),
                alert["ticker"],
                alert["nimi"],
                alert["tyyppi"],
                alert["prosentti"],
                alert["hinta_luontihetkella"],
                alert["luotu"],
            ),
        )

    def remove_alert(self, user_id: int, nimi: str) -> int:
        before = self.fetchone("SELECT COUNT(*) AS count FROM telegram_alerts WHERE user_id = ?", (str(user_id),))
        self.execute(
            "DELETE FROM telegram_alerts WHERE user_id = ? AND UPPER(nimi) = UPPER(?)",
            (str(user_id), nimi),
        )
        after = self.fetchone("SELECT COUNT(*) AS count FROM telegram_alerts WHERE user_id = ?", (str(user_id),))
        return int(before["count"]) - int(after["count"]) if before and after else 0

    def save_telegram_report(self, message_id: int, full_report: str, state: dict[str, Any]) -> None:
        self.execute(
            """
            INSERT INTO telegram_reports (message_id, full_report, state_json)
            VALUES (?, ?, ?)
            ON CONFLICT (message_id) DO UPDATE
                SET full_report = excluded.full_report,
                    state_json = excluded.state_json
            """,
            (str(message_id), full_report, json.dumps(state, ensure_ascii=False, default=str)),
        )

    def get_telegram_report(self, message_id: int) -> tuple[str | None, dict[str, Any] | None]:
        row = self.fetchone(
            "SELECT full_report, state_json FROM telegram_reports WHERE message_id = ?",
            (str(message_id),),
        )
        if not row:
            return None, None
        state = json.loads(row["state_json"]) if row.get("state_json") else None
        return row["full_report"], state


_DEFAULT_STORAGE: Storage | None = None


def get_storage(database_url: str | None = None) -> Storage:
    """Palauta lazy singleton oletus-DB:lle."""
    global _DEFAULT_STORAGE
    if database_url is not None:
        return Storage(database_url)
    if _DEFAULT_STORAGE is None:
        _DEFAULT_STORAGE = Storage()
    return _DEFAULT_STORAGE
